### ISSUE TITLE
Any documentation or examples?

### ISSUE THREAD

**Issue by JustMaier** [agileharbor/shipStationAccess#1]
Hey I'm interested in using this library, but I can't seem to find any documentation or examples of how to use it. Are these available somewhere?

**Comment by DmytroSV** [comment]
Un‎fortunately we have no documentation. This lib has been developed for our needs, bun feel free to ask any questions.                                                                                                                                                                                                                                                                          Отправлено с моего смартфона BlackBerry 10.                                                                                                                                                                                                                                         От: Justin MaierОтправлено: пятница, 29 мая 2015 г., 20:58Кому: agileharbor/shipStationAccessОтветить: agileharbor/shipStationAccessТема: [shipStationAccess] Any documentation or examples? (#1)Hey I'm interested in using this library, but I can't seem to find any documentation or examples of how to use it. Are these available somewhere?

—Reply to this email directly or view it on GitHub.

**Comment by JustMaier** [comment]
Ok, Thanks @DmytroSV
